# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8343d140f67a62dd9c8c59e492e2ecddcf93a8140b6835d8de8fea6659832e094f2fb7efb471fc2338edd94a840ab9c46c35af2e78fe64a5930bda499cc8c515

test:
  secret_key_base: 54b9f3e4b497fba9d2b25c7a3b08cc967b430fb098f089c8a8f15801b7cebb086033b300c93ceb9d855c243331aa2127038936c57ea4f029e08cb2f16067563b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
